### ISSUE TITLE
passthrough and phantomjs regression in 0.10.1 vs 0.10.0

### ISSUE THREAD

**Issue by kielni** [pretenderjs/pretender#121] opened 2015-10-23 22:04 UTC
I'm using pretender with ember-cli-blanket.  I have this in my fixtures so that the code coverage report won't be intercepted:

```
this.post('/write-blanket-coverage', this.passthrough);
```

I was running 0.10.0, and the coverage report was working fine in both the browser and command line.  

I updated to 0.10.1, and it worked fine in the browser but the coverage report was not written when running on the command line with phantomjs (1.9.8).  

I had trouble with this before, which I think was related to this: https://github.com/pretenderjs/pretender/pull/76 (and updating to 0.10.0 fixed it).

**Comment by bantic** [comment] 2015-10-25 18:53
@kielni Can you give any more details? Does the test output indicate any failures? Any chance you can [upgrade to Phantom 2.0](https://mediocre.com/forum/topics/phantomjs-2-and-travis-ci-we-beat-our-heads-against-a-wall-so-you-dont-have-to) and see if it works that way? Are you using ember-cli-mirage, or just Pretender directly?

**Comment by bantic** [comment] 2015-10-25 20:36
@kielni I created a [test ember-cli app](https://github.com/bantic/test-ember-blanket/commit/2f6fffeeea0e7c012275d26f09fd9aca8976e323) that uses ember-cli-blanket and pretender 0.10.1. 

It uses a [fork I made of ember-cli-blanket](https://github.com/sglanzer/ember-cli-blanket/compare/master...bantic:add-logging) that adds some logging, in particular a "RUNNING REPORTER" message that is output by the ember-cli app when it receives a `post` to `'/write-blanket-coverage'`.

I'm running it with pretender 0.10.1 and phantom 1.9 on travis and it appears to send the test coverage just fine. To double-check I created branches that use [no pretender](https://travis-ci.org/bantic/test-ember-blanket/builds/87353896), [pretender with passthrough](https://travis-ci.org/bantic/test-ember-blanket/builds/87353944), and [pretender without passthrough](https://travis-ci.org/bantic/test-ember-blanket/builds/87353962).

As expected, the branches without pretender and using pretender with passthrough both log a message that the reporting coverage is being saved. The client-side logs around the ajax call to save coverage do not get logged at travis, though. That appears be a race condition with the end of the tests, but the coverage does still get saved.

![image](https://cloud.githubusercontent.com/assets/2023/10717698/396448b8-7b36-11e5-953c-ae874c60117a.png)

Let me know if there's some more detail you can provide to help narrow down your issue.

**Comment by kielni** [comment] 2015-10-27 15:56
I am using pretender directly.  I was using ember 1.12 but tested with 1.13 and saw the same behavior.

I think it has something to do with async helpers in the tests and the race condition. I'll try to simplify some tests and see what I can find.

**Comment by kielni** [comment] 2015-10-27 21:55
With pretender 0.10.1, Ember 1.13.10, bantic/ember-cli-blanket#add-logging and this set of tests:

````
module('Acceptance | dashboard', {
    beforeEach: function() {
        server = new Pretender(Fixtures.responses);
        application = startApp();
    },

    afterEach: function() {
        Ember.run(application, 'destroy');
    }
});

test('visiting dashboard', function(assert) {
    visit('/login');
    andThen(function() {
        assert.equal(currentURL(), '/login');
    });
});

test('second test', function(assert) {
    assert.ok(1);
});
````
If I comment out the second test, I do get the coverage report.  If I run it with both tests, I don't get the coverage report.  

I tried turning on blanket's debugging (`debug: true` in tests/blanket-options.js) and removing some of it.  With both tests:

````
rm -f coverage.json ; ember test --module Acceptance%20%7C%20dashboard | grep -E "BLANKET-Test|REPORTER"; ls coverage.json
            BLANKET-Test event started
            BLANKET-Test event done
            BLANKET-Test event started
            BLANKET-Test event done
ls: coverage.json: No such file or directory
````

with just the first test:
````
rm -f coverage.json ; ember test --module Acceptance%20%7C%20dashboard | grep -E "BLANKET-Test|REPORTER"; ls coverage.json
RUNNING REPORTER
            BLANKET-Test event started
            BLANKET-Test event done
coverage.json
````

**Comment by bantic** [comment] 2015-11-02 13:53
@kielni Thanks for the detailed reproduction steps here. I will take a look at this soon.

**Comment by lolmaus** [comment] 2016-01-05 11:43
I ran into this issue when using Ember CLI Mirage in the browser.

The reason this happens is that this function is called with `undefined` for `event`: https://github.com/pretenderjs/pretender/blob/master/pretender.js#L179

**Comment by sudrao** [comment] 2016-01-08 23:04
Please try out this fix: https://github.com/pretenderjs/pretender/pull/139/files using this in bower.json: "pretender": "https://github.com/sudrao/pretender.git#~0.10.3"

**Comment by john-kurkowski** [comment] 2016-02-19 02:14
@sudrao tried your fork in my bower.json, fixed my issue. Thanks!

**Comment by stefanpenner** [comment] 2017-07-16 18:50
https://github.com/pretenderjs/pretender/pull/139#issuecomment-241094371 describes the root cause of the issue, being that the previous pretender server was not being shutdown correctly, before starting another.

I'm going to close this. If the above is not correct, please provide a reproduction and we can gladly reopen.

**Closed by stefanpenner** 2017-07-16 18:50 UTC
